function [data, mask] = load_raw_data_masked(p, sub_id, mask_only)

% function [data, mask] = load_raw_data_masked(p, i_sub, mask_only)
%
% Load (realigned) raw data, masked with ROI.
% Uses an adapted version of spmReadVolsMasked.m from the cvmanova toolbox
% by Carsten Allefeld, accessible at
% https://github.com/allefeld/cvmanova/releases.
%
% Input:
%   - p: Structure with analysis parameters.
%   - sub_id: ID of the current subject.
%   - mask_only: Set to 1 to only load the mask image.
%
% Output:
%   - data: [n_tr ,n_voxel, n_run] array with data.
%   - mask: [x,y,z] array with ROI mask.
%
% Simon Weber, sweber@bccn-berlin.de, 2021

% Initialize output variable
data = [];
mask = [];

% Get subject ID as string
sub_str = num2str(sub_id,'%02i');

% Load whole brain mask generated by SPM during preprocesing
spm_mask = fullfile(p.dirs.data, 'Nifti', ['sub-' sub_str], 'rois', 'mask.nii');
if ~exist(spm_mask, 'file')
    warning('Subject %d - fMRI data connot be loaded.', sub_id);
    return;
end
spm_mask = spm_vol(fullfile(p.dirs.data, 'Nifti', ['sub-' sub_str], 'rois', 'mask.nii'));
spm_mask = spm_read_vols(spm_mask);

% Load ROI mask, should be located in the subject-specific folder 'rois'.
% Else, use SPM whole brain mask to load all brain voxels.
if isfield(p.psvr, 'roi') && ~isempty(p.psvr.roi)

    roi_dir = fullfile(p.dirs.data, 'Nifti', ['sub-' sub_str], 'rois');
    mask_hdr = spm_vol(fullfile(roi_dir, [p.psvr.roi '.nii']));
    mask = spm_read_vols(mask_hdr);

    % Mask ROI mask with SPM mask so that only brain voxels are included
    mask(find(spm_mask==0)) = 0;
else
    warning('No ROI mask defined, loading all brain voxels.')
    mask = spm_mask;
end

% Get filenames of realigned fMRI images
files = {};
for i_ses = 1:p.n_session
    ses_str = num2str(i_ses,'%02i');
    vols = dir(fullfile(p.dirs.data, 'Nifti', ['sub-' sub_str], ['ses-' ses_str], 'func', ['rsub*' p.img.filter '*.nii']));
    files = [files; arrayfun(@(x) fullfile(x.folder, x.name), vols, 'UniformOutput', false)];
end

% Return if only mask image should be loaded
if exist('mask_only','var') && mask_only == 1
    return;
end

% Load data using spmReadVolsMasked.m
for i_file = 1:numel(files)
%     parfor i_file = 1:numel(files)
    data(:,:,i_file) = spmReadVolsMasked(files{i_file}, mask, 1);
end
